<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="../view/css/global.css">
    <link rel="stylesheet" href="../view/css/normalize.css">
    <link rel="stylesheet" href="../view/css/fonts">
    <link rel="stylesheet" href="../view/css/homeView.css">
    <link rel="stylesheet" href="../view/css/workView.css">
    <link rel="stylesheet" href="../view/css/textsView.css">
    <link rel="stylesheet" href="../view/css/cvView.css">
    <title>Amandine Simonnnet</title>
</head>
<body>
<header>
    <h1><a href="home.php"> AMANDINE SIMONNET</a></h1>
    <h2><?=htmlspecialchars ($mail) ?></h2>
    <nav>
        <a href="work.php?id=54">TRAVAUX</a>
        <a href="cv.php">CV</a>
        <a href="../images/PDF/portefolio_simonnet.pdf"download="portefolio_simonnet.pdf">PDF</a>
        <a href="text.php">TEXTES</a>
    </nav>
</header>
<main>
    <?php include $template.".phtml" ?>
</main>
<footer>
    <div class="event">
    <p><strong>15/15/15</strong>expo a pouet</p>
    </div>
    <h4>Droit d'auteur</h4>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eu consecte
        tur sem. In molestie non metus nec hendrerit. Sed pulvinar magna id enim
        feugiat sodales. Nulla facilisi. In convallis, mi vel vulputate rhoncus,
        libero urna ullamcorper odio, vitae sollicitudin nisi mi vel ex. Ut orci
        ipsum, dignissim vitae velit et, ullamcorper ultricies augue. Nulla et
        mi
        ac nunc suscipit posuere. Nam eu pretium lacus. Mauris in dapibus ante.
        Ut nulla ante, aliquet et sapien ut, accumsan dapibus turpis. Sed
        ultrices eros ut blandit pulvinar.</p>
</footer>
</body>
</html>